### ISSUE TITLE
How to get the connectionID? 

### ISSUE THREAD

**Issue by th317erd** [opentok/OpenTok-Ruby-SDK#209]
Some of the methods defined in this SDK define a need for a `connection_id` (i.e. `forceDisconnect`), however, the documentation (or should I say the VERY LACKING documentation) doesn't specify in the slightest how to get a connection ID for a stream. How does one get connection_ids? We need to forceDisconnect server-side... and so need a connection_id.

**Comment by benhayehudi** [comment]
Hi there, 

You'll need to send the connection ID from the frontend back to your Ruby backend in order to obtain and utilize the connection ID in methods such as `#forceDisconnect`. 

When a client joins a session you will receive a `connectionCreated` event that contains the connection object. If you create an eventListener for that event, you can catch it when it occurs and capture the data in the object to send to your backend.

There is some more information in the documentation on it here: https://tokbox.com/developer/guides/connect-session/js/index.html#detect_other_connections

All the best,

Ben

**Comment by th317erd** [comment]
Is there any good reason for this architecture design? Why not just have your API be able to fetch connection_ids?

**Comment by benhayehudi** [comment]
This document does a good job of covering why video is architected the way it is, with the responsibilities delineated between client side and server side code: https://tokbox.com/developer/guides/basics/

All the best.

**Comment by alex-fe** [comment]
Been struggling with this in Python; thought it was just me. This delineation is so silly.
