### ISSUE TITLE
EveryTime I refresh page new subscriber is added for multiple participant

### ISSUE THREAD

**Issue by kamalpandey** [opentok/OpenTok-Ruby-SDK#210]
```
onSessionStreamCreated = event => {
    let subscriber = this.state.otSession.subscribe(event.stream, null, this.defaultSubscriberProps, error => {
      if (error) {
        console.error('There was an error subscribing: ', error.name, error.message);
      }
    });
    if (event.stream.videoType == 'screen') {
      subscriber.on('videoElementCreated', this.onPublisherScreenElement);
      this.setState(() => {
        return { screenSubscriber: subscriber };
      });
    }
    else {
   
        this.setState( prevState => {
          return {
            subscribers: [...this.state.subscribers, subscriber],
          };
        },
        () => {
          subscriber.on('videoElementCreated', this.onSubscriberVideoElement);
            this.startSessionTimer();
          }
        );
        this.setState(() => {
          return { subscribers: [subscriber] };
        });
      
    }
  };
```

**Comment by benhayehudi** [comment]
Hi there @kamalpandey, 

It's difficul to ascertain exactly what the issue is without a more involved conversation. Might you be able to join the Vonage Community Slack and pose the question in the #video-api channel, where we can engage more fully with you on your specific implementation? Details to join Slack can be found here: https://developer.nexmo.com/community/slack

Thanks,

Ben

**Comment by kellyjandrews** [comment]
I think what may be happening is that the state isn't properly removing the old stream, and when refreshing the duplicate videos show because both streams end up being active. 

You should be able to check if there is still a stream before creating a new one using `getSubscribersForStream(stream)` on the `session`. For reference - https://tokbox.com/developer/sdks/js/reference/Session.html#getSubscribersForStream

This StackOverflow user had a similar issue with Angular - https://stackoverflow.com/questions/45078172/opentok-tokbox-multiple-copies-of-same-subscriber-intermittently-in-angular-4 and resolved it this way.  

Hope some of this helps.
