### ISSUE TITLE
Missing equivalent forceMute or forceMuteAll functionality

### ISSUE THREAD

**Issue by kimyu92** [opentok/OpenTok-Ruby-SDK#226]
Issue: It seems like ruby sdk is less on par with js sdk for https://tokbox.com/developer/guides/moderation/js/

Currently, using ruby sdk there is no way to mute the stream for SIP

Would it be possible to review this PR and merge into sdk?
https://github.com/Vonage/mute-all-OpenTok-Ruby-SDK/pull/1

Also, if this change mades into the sdk, there should be `forceUnmute` or `forceUnmuteAll` to reverse these actions, right?

**Comment by dominikduda** [comment]
Doubling down on this. 

I need to mute, then unmute a single stream. 
Is it possible currently?

**Comment by jalex1508** [comment]
Interested. 
Is this issue still active?

**Comment by dominikduda** [comment]
It would be awesome if you could make the video API team implement the methods mentioned in this issue.

I have the following case in my app.

1. User A is connected through phone SIP into the session.
2. User B is initializing connection through phone SIP into the session.

Actual result:
User A hears a ringing signal from user B's stream (before he even answers the call).

Expected result:
User B does not hear ringing noise from phone calls that are not yet answered.

For browser clients, we are working around that by muting the phone call until it is actually answered.
We have no way to do that for phone calls already in the session. 
We could use the mute feature and make user B unmute himself when he joins the session but that is inconvenient.
It adds additional action to perform for user B and we don't want that. We just want to unmute him when he answers automatically.

This may be an edge case because we are integrating opentok with Twilio.

**Comment by superchilled** [comment]
Hi all. Apologies for the delayed response on this (I've been on vacation for the last two weeks).

So, I followed this up with the engineering team, and the fact that there is no force unmute functionality is by design for privacy reasons (i.e. if someone mutes, they may not necessarily want to be unmuted without their consent).

Obviously, this doesn't really help in the particular edge case described by @dominikduda, but unfortunately I can't see this being implemented as a feature on the API (and therefore no way to add it to the SDK).
