### ISSUE TITLE
multiArchiveTag is not passed along to api when specified during archive creation.

### ISSUE THREAD

**Issue by DropsOfSerenity** [opentok/OpenTok-Ruby-SDK#268]
It looks like `multiArchiveTag` and `streamMode` are not passed correctly to the api when creating an archive, due to `valid_opts` removing them. This does not match the documentation that says these are valid options.

We currently monkey patch OpenTok to solve this issue for us, but would like to fix the upstream issue here.

I've opened an [associated PR](https://github.com/opentok/OpenTok-Ruby-SDK/pull/269) that fixes this issue.

**Comment by superchilled** [comment]
Hi @DropsOfSerenity. Thanks for opening this issue, and for the PR. I'll review the PR and hopefully should be able to get it merged soon.

**Comment by superchilled** [comment]
Hi @DropsOfSerenity, this has been fixed in https://github.com/opentok/OpenTok-Ruby-SDK/releases/tag/v4.8.1, and is available on [RubyGems](https://rubygems.org/gems/opentok/versions/4.8.1).

Note: I made some additional ammendments after merging [your PR](https://github.com/opentok/OpenTok-Ruby-SDK/pull/269) which can be seen in [this PR](https://github.com/opentok/OpenTok-Ruby-SDK/pull/270).

Specifically, I changed `multi_archive_tag` and `stream_mode` in `valid_opts` to snake case from camel case, since this is more idiomatic and also in keeping with the code style of the library (although the API expects the properties in camel case, the top-level keys get automatically converted [here](https://github.com/opentok/OpenTok-Ruby-SDK/blob/6632bb6752f29f00194be5b92f468db11acdeec5/lib/opentok/client.rb#L69) before the request is made by the `Client` object. I just thought I should mention this, since your PR used the camel cased versions, I assume your monkey-patch does too, so if you want to remove your monkey patch in order to use 4.8.1, you'll need to update the keys in the `options` hash to the snake cased versions wherever you call `Archives#create`. (I've also updated the docs comments accordingly, which I'm guessing is where you initially got the key names from for your PR).

Thanks again for raising the issue, and for submitting the PR.
